apiVersion: v1
data:
  version: sha-9a5c33f
kind: ConfigMap
metadata:
  name: k8s-helloworld-configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: version
          valueFrom:
            configMapKeyRef:
              key: version
              name: k8s-helloworld-configmap
        image: ghcr.io/robert-rino/heroku-alpinehelloworld:sha-9a5c33f
        name: server
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
