apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-helloworld
  annotations:
    kubernetes.io/ingress.global-static-ip-name: k8s-helloworld
    networking.gke.io/managed-certificates: k8s-helloworld-managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: k8s-helloworld.nino.run
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: k8s-helloworld
            port:
              number: 8080
